name: Build Flutter APK

on:
  push:
    branches:
      - main # Replace 'main' with your default branch name if different
  pull_request:

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # e.g., '3.13.2' or 'stable'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build APK
      - name: Build APK
        run: flutter build apk --release


      # Step 5: Create a GitHub Release and upload the APK
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0v0.${{github.run_number}}
          name: "Release v0.${{github.run_number}}"
          body: "This is the ${{github.run_number}} release of the app."
          draft: false
          prerelease: false

      # # Step 5: release
      # - name: push to release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/release/*"
      #     tag : v0.0.1

      # # Step 5: Upload APK as an artifact
      # - name: Upload APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk
